---
- name: win_copy
  hosts: all
  become: false
  gather_facts: false
  vars:
    source: "utils/"
    destination: "C:\\ansible-utils\\"
  tasks:
    - name: test connection
      ansible.windows.win_ping:
    - name: copy utils files
      ansible.windows.win_copy:
        src: "{{ source }}"
        dest: "{{ destination }}"
